name: Build
on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

        run: npm ci

      - name: Build grammars
        run: npm run build

      - name: Build extension
        run: npm run tsc

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1.5.0
        with:
          pat: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: true