name: Build
on:
  push:
    branches:
      - master

jobs:
  run-tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: Run-Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare
        uses: actions/setup-node@v3
        with:
          # Do not include registy url here, it creates a .npmrc which prevents
          # semantic-release from authenticating with npm
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build grammars
        run: npm run build

      - name: Build extension
        run: npm run tsc

      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     VSCE_PAT: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
      #   run: npx semantic-release

      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1.5.0
        with:
          pat: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
          preRelease: true